name: Post to X from Reddit RSS

on:
  schedule:
    - cron: "0 */3 * * *"  # كل 3 ساعات
  workflow_dispatch:        # يسمح بتشغيله يدويًا أيضًا

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug secrets
        run: echo $API_KEY

      - name: Run bot
        run: python src/instantly-tweet-from-openai.py
